version: '3'

volumes:
  static:
  postgres_data:

services:
  bot:
    build: .
    restart: always
    entrypoint: ./entrypoint-bot.sh
    env_file:
      - ./.env
    command: ./manage.py runbot
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    entrypoint: ./entrypoint.sh
    volumes:
      - static:/code/static/
    depends_on:
      - bot
    ports:
      - "7999:7999"
    env_file:
      - ./.env
    tty: true
    command: ./manage.py runserver 0.0.0.0:7999
  nginx:
    image: nginx:1.19.3  
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - db
