# Generated by Django 4.2.4 on 2023-08-01 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='Telegram id')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='bot.entity', verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Number')),
                ('link', models.CharField(max_length=72, verbose_name='Name')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='bot.entity', verbose_name='Name')),
            ],
        ),
    ]
