# Generated by Django 4.2.4 on 2023-08-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='tg_id',
            new_name='tg',
        ),
    ]
