# Generated by Django 4.2.4 on 2023-08-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_tg_id_observation_tg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='name',
            new_name='entity',
        ),
    ]
