# Generated by Django 4.2.4 on 2023-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_case_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
